name: Crown Forecaster Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test with the dotnet CLI
      run: dotnet test

  aws-deploy:
    environment: prod
    runs-on: ubuntu-latest
    needs: [build-and-test]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-1'

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Setup NodeJS Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: CDK Synth
        run: |
          cd './CrownForecaster.Deployment/CrownForecaster.Deployment'
          cdk synth --require-approval=never

      - name: CDK Deploy
        run: |
          cd './CrownForecaster.Deployment/CrownForecaster.Deployment'
          cdk deploy --require-approval=never